### PR TITLE
no default namespace policy added

### PR DESCRIPTION
**Pull request by arindam-b**
In the quickstart, add a policy which does not allow to use default namespace.

### CODE REVIEW

**Comment by bourgeoisor** [comment]
@arindam-b could you provide a bit more information on the context behind this PR?

**Comment by arindam-b** [comment]
@bourgeoisor This is about a quickstart example, I wanted to enforce few policies but basic few checks should have been there. That's why added a simple opa policy to disallow default namespace usage for the mentioned application.

**Comment by bourgeoisor** [comment]
This quickstart sample is leveraged here: https://cloud.google.com/anthos-config-management/docs/tutorials/create-configure-cluster and is not meant to show an exhaustive list of all possible policies.

I realize that this is not clear from the lack of README in the directory, so I will work on improving the documentation in this repo and leave this PR open in the meantime. Once I have a docs PR open, I will close this one.

**Comment by bourgeoisor** [comment]
Created https://github.com/GoogleCloudPlatform/anthos-config-management-samples/pull/79
Closing this PR.

**Pull request closed without merging**
